/* @header@ */

#include "emu/emu_cpu_data.h"

int64_t max_inttype_borders[][2][2] =                                            
{                                                                          
	{                                                                      
		{0,0},                                                             
		{0,0},                                                             
	},                                                                     
	{                                                                      
		{MIN_INT8, MAX_INT8},                                              
		{MIN_UINT8, MAX_UINT8},                                            
	},                                                                     
	{                                                                      
		{MIN_INT16, MAX_INT16},                                            
		{MIN_UINT16, MAX_UINT16},                                          
	},                                                                     
	{                                                                      
		{0,0},                                                             
		{0,0},                                                             
	},                                                                     
	{                                                                      
		{MIN_INT32, MAX_INT32},                                            
		{MIN_UINT32, MAX_UINT32},                                          
	}                                                                      
};                                                                          


/*
for i in AAA AAD AAM AAS ADC ADD AND ARPL BOUND BSF BSR BSWAP BT BTS BTR BTC CALL CBW CLC CLD CLI CLTS CMC CMOVcc CMP CMPS CMPXCHG CMPXCHG8B COMSID COMISS CPUID CWD DAA D DEC DIV ENTER ESC FCMOVcc FCOMI FCOMIP FUCOMI FUCOMIP HLT IDIV IMUL IN INC INS INT INTO INVD INVLPG UCOMSID UCOMISS IRET Jcc JCXZ JMP LAHF LAR LDS LES LSS LFS LGS LEA LEAVE LGDT LIDT LLDT LMSW LOCK LODS LOOP LOOPE LOOPNE LSL LTR MONITOR MWAIT MOV MOVS MOVSX MOVZX MUL NEG NOP NOT OR OUT OUTS POP POPA POPF PUSH PUSHA PUSHF RCL_1 RCR_1 RCL_count RCR_count RDMSR RDPMC RDTSC REP REPE REPNE RET ROL_1 ROR_1 ROL_count ROR_count RSM SAHF SAL_1 SAR_1 SHL_1 SHR_1 SAL_count SAR_count SHL_count SHR_count SBB SCAS SETcc SGDT SIDT SLDT SMSW SHLD SHRD STC STD STI STOS STR SUB TEST UD2 VERR VERRW WAIT WBINVD WRMSR XADD XCHG XLAT XOR; do  ys=$(echo $i | tr '[A-Z]' '[a-z]');  echo -e -n "
{ // EMU_INSTR_$i
.instrstr      = \"$ys\",
.test_flags    = 0,
.modify_flags  = 0,
.reset_flags   = 0,
.set_flags     = 0,
.restore_flags = 0,
},"; done
*/

#define FLAG_SET(fl) (1 << (fl))

struct emu_instruction_eflag_effect instruction_flag_sets[] = 
{
	{ // EMU_INSTR_AAA
		.instrstr      = "aaa",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_AAD
		.instrstr      = "aad",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_AAM
		.instrstr      = "aam",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_AAS
		.instrstr      = "aas",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ADC
		.instrstr      = "adc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ADD
		.instrstr      = "add",
		.test_flags    = 0,
		.modify_flags  = ( FLAG_SET(f_of) | FLAG_SET(f_sf) | FLAG_SET(f_zf) | FLAG_SET(f_af) | FLAG_SET(f_pf) | FLAG_SET(f_cf)),
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_AND
		.instrstr      = "and",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ARPL
		.instrstr      = "arpl",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BOUND
		.instrstr      = "bound",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BSF
		.instrstr      = "bsf",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BSR
		.instrstr      = "bsr",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BSWAP
		.instrstr      = "bswap",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BT
		.instrstr      = "bt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BTS
		.instrstr      = "bts",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BTR
		.instrstr      = "btr",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_BTC
		.instrstr      = "btc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CALL
		.instrstr      = "call",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CBW
		.instrstr      = "cbw",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CLC
		.instrstr      = "clc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CLD
		.instrstr      = "cld",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CLI
		.instrstr      = "cli",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CLTS
		.instrstr      = "clts",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CMC
		.instrstr      = "cmc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CMOVcc
		.instrstr      = "cmovcc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CMP
		.instrstr      = "cmp",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CMPS
		.instrstr      = "cmps",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CMPXCHG
		.instrstr      = "cmpxchg",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CMPXCHG8B
		.instrstr      = "cmpxchg8b",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_COMSID
		.instrstr      = "comsid",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_COMISS
		.instrstr      = "comiss",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CPUID
		.instrstr      = "cpuid",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_CWD
		.instrstr      = "cwd",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_DAA
		.instrstr      = "daa",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_DAS
		.instrstr      = "das",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_DEC
		.instrstr      = "dec",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_DIV
		.instrstr      = "div",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ENTER
		.instrstr      = "enter",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ESC
		.instrstr      = "esc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_FCMOVcc
		.instrstr      = "fcmovcc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_FCOMI
		.instrstr      = "fcomi",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_FCOMIP
		.instrstr      = "fcomip",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_FUCOMI
		.instrstr      = "fucomi",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_FUCOMIP
		.instrstr      = "fucomip",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_HLT
		.instrstr      = "hlt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_IDIV
		.instrstr      = "idiv",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_IMUL
		.instrstr      = "imul",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_IN
		.instrstr      = "in",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_INC
		.instrstr      = "inc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_INS
		.instrstr      = "ins",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_INT
		.instrstr      = "int",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_INTO
		.instrstr      = "into",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_INVD
		.instrstr      = "invd",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_INVLPG
		.instrstr      = "invlpg",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_UCOMSID
		.instrstr      = "ucomsid",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_UCOMISS
		.instrstr      = "ucomiss",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_IRET
		.instrstr      = "iret",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_Jcc
		.instrstr      = "jcc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_JCXZ
		.instrstr      = "jcxz",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_JMP
		.instrstr      = "jmp",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LAHF
		.instrstr      = "lahf",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LAR
		.instrstr      = "lar",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LDS
		.instrstr      = "lds",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LES
		.instrstr      = "les",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LSS
		.instrstr      = "lss",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LFS
		.instrstr      = "lfs",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LGS
		.instrstr      = "lgs",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LEA
		.instrstr      = "lea",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LEAVE
		.instrstr      = "leave",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LGDT
		.instrstr      = "lgdt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LIDT
		.instrstr      = "lidt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LLDT
		.instrstr      = "lldt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LMSW
		.instrstr      = "lmsw",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LOCK
		.instrstr      = "lock",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LODS
		.instrstr      = "lods",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LOOP
		.instrstr      = "loop",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LOOPE
		.instrstr      = "loope",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LOOPNE
		.instrstr      = "loopne",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LSL
		.instrstr      = "lsl",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_LTR
		.instrstr      = "ltr",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MONITOR
		.instrstr      = "monitor",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MWAIT
		.instrstr      = "mwait",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MOV
		.instrstr      = "mov",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MOVS
		.instrstr      = "movs",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MOVSX
		.instrstr      = "movsx",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MOVZX
		.instrstr      = "movzx",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_MUL
		.instrstr      = "mul",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_NEG
		.instrstr      = "neg",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_NOP
		.instrstr      = "nop",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_NOT
		.instrstr      = "not",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_OR
		.instrstr      = "or",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_OUT
		.instrstr      = "out",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_OUTS
		.instrstr      = "outs",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_POP
		.instrstr      = "pop",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_POPA
		.instrstr      = "popa",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_POPF
		.instrstr      = "popf",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_PUSH
		.instrstr      = "push",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_PUSHA
		.instrstr      = "pusha",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_PUSHF
		.instrstr      = "pushf",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RCL_1
		.instrstr      = "rcl_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RCR_1
		.instrstr      = "rcr_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RCL_count
		.instrstr      = "rcl_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RCR_count
		.instrstr      = "rcr_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RDMSR
		.instrstr      = "rdmsr",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RDPMC
		.instrstr      = "rdpmc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RDTSC
		.instrstr      = "rdtsc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_REP
		.instrstr      = "rep",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_REPE
		.instrstr      = "repe",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_REPNE
		.instrstr      = "repne",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RET
		.instrstr      = "ret",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ROL_1
		.instrstr      = "rol_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ROR_1
		.instrstr      = "ror_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ROL_count
		.instrstr      = "rol_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_ROR_count
		.instrstr      = "ror_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_RSM
		.instrstr      = "rsm",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SAHF
		.instrstr      = "sahf",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SAL_1
		.instrstr      = "sal_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SAR_1
		.instrstr      = "sar_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SHL_1
		.instrstr      = "shl_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SHR_1
		.instrstr      = "shr_1",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SAL_count
		.instrstr      = "sal_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SAR_count
		.instrstr      = "sar_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SHL_count
		.instrstr      = "shl_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SHR_count
		.instrstr      = "shr_count",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SBB
		.instrstr      = "sbb",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SCAS
		.instrstr      = "scas",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SETcc
		.instrstr      = "setcc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SGDT
		.instrstr      = "sgdt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SIDT
		.instrstr      = "sidt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SLDT
		.instrstr      = "sldt",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SMSW
		.instrstr      = "smsw",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SHLD
		.instrstr      = "shld",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SHRD
		.instrstr      = "shrd",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_STC
		.instrstr      = "stc",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_STD
		.instrstr      = "std",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_STI
		.instrstr      = "sti",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_STOS
		.instrstr      = "stos",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_STR
		.instrstr      = "str",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_SUB
		.instrstr      = "sub",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_TEST
		.instrstr      = "test",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_UD2
		.instrstr      = "ud2",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_VERR
		.instrstr      = "verr",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_VERRW
		.instrstr      = "verrw",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_WAIT
		.instrstr      = "wait",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_WBINVD
		.instrstr      = "wbinvd",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_WRMSR
		.instrstr      = "wrmsr",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_XADD
		.instrstr      = "xadd",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_XCHG
		.instrstr      = "xchg",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_XLAT
		.instrstr      = "xlat",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	},
	{ // EMU_INSTR_XOR
		.instrstr      = "xor",
		.test_flags    = 0,
		.modify_flags  = 0,
		.reset_flags   = 0,
		.set_flags     = 0,
		.restore_flags = 0,
	}
};
